// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpaweEKVfkMtwVyjCZNwL_ulPONSfMHA0',
    appId: '1:427305522394:web:7c4245382409fd0d7801e3',
    messagingSenderId: '427305522394',
    projectId: 'app-iamoneai-c36ec',
    authDomain: 'app-iamoneai-c36ec.firebaseapp.com',
    storageBucket: 'app-iamoneai-c36ec.firebasestorage.app',
    measurementId: 'G-KT8JX23QFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZ85ooFfuLLKoIfyUL0WX-x6O6YpNdy4',
    appId: '1:427305522394:android:18d204cc288d1d967801e3',
    messagingSenderId: '427305522394',
    projectId: 'app-iamoneai-c36ec',
    storageBucket: 'app-iamoneai-c36ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5bFotiutWphATtB0rb_JQmrqwoPkJm8A',
    appId: '1:427305522394:ios:1147886567d30e0d7801e3',
    messagingSenderId: '427305522394',
    projectId: 'app-iamoneai-c36ec',
    storageBucket: 'app-iamoneai-c36ec.firebasestorage.app',
    iosClientId: '427305522394-6l2e1eq0csv611cu0qqm0uningotsj24.apps.googleusercontent.com',
    iosBundleId: 'com.example.iamoneaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5bFotiutWphATtB0rb_JQmrqwoPkJm8A',
    appId: '1:427305522394:ios:1147886567d30e0d7801e3',
    messagingSenderId: '427305522394',
    projectId: 'app-iamoneai-c36ec',
    storageBucket: 'app-iamoneai-c36ec.firebasestorage.app',
    iosClientId: '427305522394-6l2e1eq0csv611cu0qqm0uningotsj24.apps.googleusercontent.com',
    iosBundleId: 'com.example.iamoneaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpaweEKVfkMtwVyjCZNwL_ulPONSfMHA0',
    appId: '1:427305522394:web:2782ac005bd527ff7801e3',
    messagingSenderId: '427305522394',
    projectId: 'app-iamoneai-c36ec',
    authDomain: 'app-iamoneai-c36ec.firebaseapp.com',
    storageBucket: 'app-iamoneai-c36ec.firebasestorage.app',
    measurementId: 'G-XG8MSQ277P',
  );
}
